neptune-ai/neptune-client

neptune/client.py
neptune/experiment.py
neptune/project.py
neptune/session.py

- Add `get_project` method to Session object

Implement basic experiment creation

---

neptune/projects.py

* remove deprecated state transition calls

Remove deprecated API calls

---

neptune/__init__.py
neptune/client.py
neptune/experiments.py
neptune/projects.py

* Implement properties setting during experiment execution
* Change tag manipulation methods
* Send exception value in traceback for failed experiment

Add tags and properties handling

---

neptune/projects.py

Print link to experiment

---

neptune/client.py

Fix compatibility with python 3

---

neptune/internal/streams/stdstream_uploader.py

Add `fileno` method to streams wrappers

---

neptune/internal/channels/channels_values_sender.py

This was breaking user's code when user's file was named test.py

Fix queue import from future

---

neptune/__init__.py
neptune/exceptions.py
neptune/internal/backends/credentials.py
neptune/projects.py
neptune/sessions.py
tests/neptune/test_project.py

Added:
* links to relevant docs in error messages
* changed things to make the copy more friendly
* added colouring

Added docs links to error messages

---

.github/workflows/neptune-client.yml
neptune/experiments.py
neptune/internal/utils/image.py
test_requirements.txt
tests/neptune/internal/utils/test_image.py
tox.ini

* added logging of tensorflow tensor as image
* added logging of pytorch tensor as image
* fixed scaling of logging numpy arrays as image

Added logging of tensorflow and pytorch tensors as image

---

neptune/alpha/experiment.py
neptune/alpha/handler.py
neptune/alpha/internal/credentials.py
neptune/alpha/internal/init_impl.py
neptune/alpha/internal/operation_processors/async_operation_processor.py
neptune/alpha/internal/operation_processors/offline_operation_processor.py
neptune/alpha/internal/operation_processors/operation_processor.py
neptune/alpha/internal/operation_processors/sync_operation_processor.py

Add missing api_token argument to init()
Add missing disk_only argument to wait()
Add missing __delitem__ method to Experiment
Support for using Experiment as context manager
Fix local state inconsistancy in case of error in sync mdoe

Improvements

---

neptune/internal/utils/image.py

need one space between "or" and 3

One space missing in exception

---

neptune/experiments.py
neptune/internal/backends/alpha_integration_backend.py
neptune/internal/utils/alpha_integration.py

[NPT-9216] Return dict consistent with docs from get_logs()

---

neptune/new/handler.py

It should not be an aliast for assign.
It should be used only for files.

Fix update method in handler

---

neptune/new/exceptions.py
neptune/new/internal/backends/hosted_file_operations.py
neptune/new/internal/backends/hosted_neptune_backend.py
tests/neptune/new/internal/backends/test_hosted_file_operations.py
tests/neptune/new/internal/backends/test_hosted_neptune_backend.py

Additionally fix handling errors which should kill async thread
instead of just being logged.

Raise pretty StorageLimitReach error

---

neptune/internal/api_clients/hosted_api_clients/hosted_backend_api_client.py
neptune/internal/api_clients/hosted_api_clients/hosted_leaderboard_api_client.py
neptune/internal/api_clients/offline_backend.py
neptune/new/__init__.py
neptune/new/internal/get_project_impl.py
neptune/utils.py
tests/neptune/internal/backends/test_noop_object.py

- Remove unneccessary global function
- Get rid of mock dependency

Minor improvements

---

neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/operation_processors/async_operation_processor.py
neptune/new/internal/threading/daemon.py
neptune/new/internal/utils/ping_background_job.py
neptune/new/run.py
tests/neptune/new/internal/backends/test_hosted_neptune_backend.py

https://neptune-labs.atlassian.net/browse/NPT-10106

nicer shutdown procedure and lost connection handling

---

neptune/new/internal/utils/__init__.py
neptune/new/internal/utils/images.py
neptune/new/internal/utils/limits.py
tests/neptune/new/internal/utils/test_images.py

also refactored a little bit to collect all limits in single file
ref. https://neptune-labs.atlassian.net/browse/NPT-10081

update limits and limit warning messages

---

requirements.txt

https://github.com/websocket-client/websocket-client/issues/694

Downgrade websocket-client bacause of bug in 1.0.0 version

---

neptune/new/internal/utils/generic_attribute_mapper.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10191

remove git ref from mapped atom values

---

neptune/new/internal/utils/images.py
tests/neptune/new/internal/utils/test_images.py

ref. https://neptune-labs.atlassian.net/browse/NPT-9970

warning on out-of-range image pixel values

---

neptune/new/exceptions.py

• Updated links to docs
• Fixes regarding exp -> run
• Updated some error messages to be more informative

Updating error messages and links to docs

---

CHANGELOG.md
neptune/__init__.py
neptune/exceptions.py
neptune/experiments.py
neptune/new/__init__.py
neptune/new/exceptions.py
neptune/new/internal/init_impl.py
neptune/new/run.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10404

heuristics to help users who mixup legacy/new client API

---

CHANGELOG.md
neptune/new/exceptions.py
neptune/new/internal/utils/__init__.py
neptune/new/internal/utils/compatibility.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10408

exception for new integrations using old exps

---

CHANGELOG.md
neptune/new/internal/utils/git.py

Reverts neptune-ai/neptune-client#631

Revert "Checking current working directory instead of entrypoint when looking for git repository"

---

neptune/new/attributes/__init__.py
neptune/new/attributes/atoms/artifact.py
neptune/new/attributes/utils.py
neptune/new/exceptions.py
neptune/new/handler.py
neptune/new/internal/artifacts/s3.py
neptune/new/internal/artifacts/types.py
neptune/new/internal/backends/api_model.py
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend.py
neptune/new/internal/backends/neptune_backend_mock.py
neptune/new/internal/backends/offline_neptune_backend.py
neptune/new/internal/init_impl.py
neptune/new/internal/value_to_attribute_visitor.py
neptune/new/run.py
neptune/new/types/atoms/artifact.py
neptune/new/types/value_visitor.py
tests/neptune/new/attributes/atoms/test_artifact.py
tests/neptune/new/attributes/test_attribute_base.py
tests/neptune/new/internal/artifacts/test_file_hasher.py
tests/neptune/new/internal/artifacts/test_s3.py
tests/neptune/new/internal/artifacts/test_serializer.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10543

Artifact(Atom) implementation and related code

---

neptune/new/internal/artifacts/file_hasher.py
tests/neptune/new/internal/artifacts/test_file_hasher.py

make artifact file hashing compatible with backend

---

CHANGELOG.md
requirements.txt

Remember to update conda package accordingly.

Boto3 version requirement

---

CHANGELOG.md

- Boto3 non-strict requirement ([#708](https://github.com/neptune-ai/neptune-client/pull/708))
- Gracefully handle backends not supporting Artifacts ([#709](https://github.com/neptune-ai/neptune-client/pull/709))

neptune-client 0.11.0

---

CHANGELOG.md
neptune/new/internal/backends/neptune_backend_mock.py
tests/neptune/new/internal/backends/test_neptune_backend_mock.py

Closes https://github.com/neptune-ai/neptune-client/issues/663

Fixed fetching numeric values in debug mode

---

CITATION.cff

* No-code changes.
* Added citation to the repo -> easier for researchers to cite us in their work.

added file with citation details

---

neptune/management/internal/utils.py

Reverts neptune-ai/neptune-client#942

Revert "NPT-12012: fix hardcoded random suffix size"

---

e2e_tests/conftest.py
e2e_tests/management/test_management.py
neptune/management/__init__.py
neptune/management/internal/api.py
neptune/management/internal/utils.py
requirements.txt
tests/neptune/management/internal/test_utils.py
tests/neptune/new/internal/backends/test_hosted_client.py

Reverts neptune-ai/neptune-client#935

Revert "NPT-12012: add project key default generation"

---

e2e_tests/conftest.py

… on specific project's organization

NPT-12385: sleep for projectKeyCollision removal

---

neptune/management/internal/api.py

- Modify `trash_objects()` example
- Adjust wording in docstrings

Management docstring adjustments

---

README.md
src/neptune/api_exceptions.py
src/neptune/exceptions.py
src/neptune/management/internal/api.py
src/neptune/new/__init__.py
src/neptune/new/exceptions.py
src/neptune/new/handler.py
src/neptune/new/internal/hardware/gpu/gpu_monitor.py
src/neptune/new/internal/init/project.py
src/neptune/new/metadata_containers/model.py
src/neptune/new/metadata_containers/model_version.py
src/neptune/new/metadata_containers/project.py
src/neptune/new/metadata_containers/run.py
src/neptune/new/types/atoms/file.py

- Point docs URLs to new docs
- Update people section in README

Docs URL update

---

src/neptune/new/handler.py

add docstring for get_root_object()

---

CHANGELOG.md
pyproject.toml
src/neptune/new/integrations/detectron2/__init__.py

Add support for detectron2 integration

---

.pre-commit-config.yaml

bump isort version to 5.12.0

---

CHANGELOG.md
src/neptune/new/integrations/utils.py
src/neptune/new/internal/utils/stringify_value.py
src/neptune/new/utils.py
tests/unit/neptune/new/test_stringify_unsupported.py

- ~[ ] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Added support of tuple to stringify_unsupported

---

CHANGELOG.md
tests/unit/neptune/new/test_stringify_unsupported.py

- ~[ ] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Fixed lack of repr for StringifyValue

---

.github/workflows/e2e.yml
.github/workflows/unit.yml

Running tag addition without workflows

---

CHANGELOG.md

- ~[ ] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Changelog updated before release

---

.github/actions/test-unit/action.yml
.github/workflows/unit-in-pull-request.yml

Coverage combined with tests

---

CHANGELOG.md

CHANGELOG updated

---

src/neptune/metadata_containers/run.py

- ~[x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)~ (No need)
- ~[x] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Removed last_run stored in Run class

---

CHANGELOG.md
src/neptune/internal/init/run.py

Remove run param from `init_run` function

---

CHANGELOG.md
src/neptune/cli/commands.py

remove --run option from neptune sync command

---

pyproject.toml
tests/unit/neptune/new/internal/backends/test_hosted_neptune_backend.py
tests/unit/neptune/new/internal/backends/test_neptune_backend_mock.py

- ~[x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)~ (No need)
- ~[x] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Minor things

---

src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py

- ~[ ] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)~ (No need)
- ~[ ] Did you **asked the docs owner** to review all the updated user-facing interfaces?~ (No need)

Overriding get_url instead of _url property

---

CHANGELOG.md
src/neptune/__init__.py
src/neptune/constants.py
src/neptune/internal/credentials.py
src/neptune/metadata_containers/run.py
src/neptune/new/__init__.py
src/neptune/new/constants.py
tests/unit/neptune/management/internal/test_api.py
tests/unit/neptune/new/client/abstract_tables_test.py
tests/unit/neptune/new/client/test_model.py
tests/unit/neptune/new/client/test_model_version.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_log_handler.py

Remove properties and constants

---

src/neptune/handler.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py

Removed `_label` internal property

---

src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py

Metadata url refactor

---

src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py

Removed _docs_url_stop property

---

tests/unit/neptune/new/test_imports.py

Removed some imports from test imports

---

README.md
src/neptune/handler.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/run.py

Fixed positional arguments

---

src/neptune/internal/utils/run_state.py
src/neptune/metadata_containers/project.py

Run state translated only at return

---

src/neptune/common/deprecation.py
src/neptune/internal/init/run.py
src/neptune/metadata_containers/metadata_container.py

Monitoring disabled warning only when required

---

CHANGELOG.md
src/neptune/common/deprecation.py
src/neptune/common/warnings.py
src/neptune/exceptions.py
src/neptune/handler.py
src/neptune/internal/init/run.py
src/neptune/internal/utils/deprecation.py
src/neptune/legacy/internal/utils/deprecation.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/new/__init__.py
src/neptune/types/type_casting.py
tests/unit/neptune/new/internal/utils/test_deprecation.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_stringify_unsupported.py

Warning instead of an exception for unsupported types

---

tests/e2e/standard/test_fetch_tables.py

fix test_fetch_runs_table_by_state

---

src/neptune/attributes/atoms/datetime.py
src/neptune/attributes/series/series.py
src/neptune/handler.py
src/neptune/types/atoms/artifact.py
src/neptune/types/atoms/datetime.py
src/neptune/types/series/file_series.py
src/neptune/types/series/float_series.py
src/neptune/types/series/string_series.py
src/neptune/types/type_casting.py
src/neptune/utils.py
tests/unit/neptune/new/test_stringify_unsupported.py

Fixed `stringify_unsupported` various behaviours

---

src/neptune/attributes/series/series.py

Fixed length checking in extend method

---

.github/workflows/release.yml

Stop waiting when releasing a tag

---

.github/workflows/release.yml

Added force reinstall and allow pre-releases

---

src/neptune/metadata_containers/project.py

Change run state values to lower-case in docstring, to be in line with convention.

update run state values in docstring

---

.github/workflows/release.yml

Wait for green master

---

.github/workflows/integrations.yml

add support for xgboost e2e tests

---

src/neptune/attributes/series/file_series.py

fix image recognition

---

.github/actions/test-e2e/action.yml
.github/actions/test-unit-with-pull-request-coverage/action.yml
.github/actions/test-unit/action.yml

Pytest with color output

---

.github/workflows/unit-in-pull-request.yml

Added `pull_request` event to unit workflow

---

.github/pull_request_template.md

Minor fix to the language in the pull request template.

Minor PR template fix

---

.github/workflows/integrations.yml

Something changed in `detectron2` implementation and tests for python 3.7 throw `ImportError: cannot import name 'cached_property' from 'functools'`. Upgrading to 3.8 to see if it works (3.9 works fine)

Fix detectron2 e2e

---

.github/workflows/integrations.yml

As per the message I got from Hamza:
> we just noticed you might have a CI/CD job that is running continously and doing some tests? If possible could you add an env variable to the github action to say `ZENML_ANALYTICS_OPT_IN` to `false`

add relevant env var

---

CHANGELOG.md

Bump the minor

---

CHANGELOG.md
pyproject.toml
src/neptune/internal/utils/dependency_tracking.py
src/neptune/metadata_containers/run.py
tests/e2e/standard/test_init.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/internal/utils/test_dependency_tracking.py

Automatically track environment dependencies

---

CHANGELOG.md
src/neptune/common/backends/utils.py
src/neptune/common/utils.py
src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/metadata_containers/metadata_container.py

This reverts commit 4d57e74c0288c48f7604da8217ef335ce4feff61.

Revert "Fix SSL errors after forking process (#1353)"

---

CHANGELOG.md
src/neptune/api/__init__.py
src/neptune/api/exceptions_utils.py
src/neptune/api/requests_utils.py
src/neptune/common/backends/utils.py
src/neptune/common/exceptions.py
src/neptune/internal/backends/swagger_client_wrapper.py
tests/unit/neptune/new/api/__init__.py
tests/unit/neptune/new/api/test_exceptions_utils.py
tests/unit/neptune/new/api/test_requests_utils.py

Support for read-only archived project exception

---

CHANGELOG.md
src/neptune/common/backends/utils.py
src/neptune/common/utils.py
src/neptune/internal/backends/hosted_client.py
src/neptune/internal/backgroud_job_list.py
src/neptune/internal/background_job.py
src/neptune/internal/disk_queue.py
src/neptune/internal/hardware/hardware_metric_reporting_job.py
src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/internal/operation_processors/operation_processor.py
src/neptune/internal/streams/std_capture_background_job.py
src/neptune/internal/streams/std_stream_capture_logger.py
src/neptune/internal/threading/daemon.py
src/neptune/internal/utils/ping_background_job.py
src/neptune/internal/utils/traceback_job.py
src/neptune/internal/websockets/websocket_signals_background_job.py
src/neptune/metadata_containers/metadata_container.py

Fix SSL errors after forking process

---

src/neptune/exceptions.py

Provide more specific docs link in the `TypeDoesNotSupportAttributeException` message.

Link error message to docs help page

---

.github/workflows/unit-in-pull-request.yml
CHANGELOG.md
src/neptune/internal/utils/git.py

Fixed GitPython `is_dirty` failing on Windows

---

.github/workflows/unit-in-pull-request.yml
CHANGELOG.md
tests/unit/neptune/new/client/test_run.py

Restored skipped test, changelog cleanup and removed trigger for pull-requests

---

src/neptune/metadata_containers/metadata_container.py

Avoid forking when Run is stopping

---

.github/workflows/release.yml

Temporarly disable waiting for tests on release

---

CHANGELOG.md
src/neptune/attributes/series/series.py
tests/unit/neptune/new/test_stringify_unsupported.py

Fixed support of stringify value in series attributes with step

---

src/neptune/internal/utils/git.py
tests/e2e/conftest.py
tests/e2e/standard/test_init.py
tests/unit/neptune/new/internal/utils/test_git.py

fix: Fix tests with git repo

---

.github/workflows/unit-in-pull-request.yml
src/neptune/internal/utils/git.py
tests/unit/neptune/new/internal/utils/test_git.py

add index=False to git diff call + only upload if sha is not None

---

CHANGELOG.md
src/neptune/internal/utils/dependency_tracking.py
tests/e2e/standard/test_init.py

add warning for dependencies tracking if file not present

---

.github/workflows/e2e.yml
tests/e2e/standard/test_init.py

I forgot to add environment to the e2e test case - that's why it's failing in the CI

fix dep tracking e2e

---

.github/workflows/e2e.yml
tests/e2e/standard/test_init.py

adjust test_upload_dependency_file after namespace change

---

CHANGELOG.md
src/neptune/metadata_containers/run.py

try-except tracking uncommitted changes and dependencies

---

CHANGELOG.md

update changelog before release

---

.github/workflows/integrations.yml
CHANGELOG.md
pyproject.toml

add support for mlflow e2e

---

.github/workflows/unit-in-pull-request.yml
tests/unit/neptune/new/client/test_run.py

fix unittest by patching os.listdir

---

CHANGELOG.md
pyproject.toml
src/neptune/integrations/tensorboard/__init__.py

add tensorboard integration support

---

.github/workflows/integrations.yml

fix typo in mlflow e2e setup

---

CHANGELOG.md
src/neptune/common/backends/utils.py

fix: Retry request when ChunkedEncodingError occurred.

---

CHANGELOG.md
src/neptune/internal/operation_processors/sync_operation_processor.py

Fixed cleaning operation storage when using sync mode and forking

---

CHANGELOG.md
src/neptune/internal/utils/dependency_tracking.py
tests/unit/neptune/new/internal/utils/test_dependency_tracking.py

Fix `FileDependenciesStrategy` when the dependency file is in a folder

---

.github/workflows/e2e.yml
CHANGELOG.md
src/neptune/metadata_containers/run.py
tests/e2e/standard/test_init.py
tests/unit/neptune/new/client/test_run.py

Allow disabling git_ref by passing False

---

CHANGELOG.md
src/neptune/utils.py
tests/unit/neptune/new/test_stringify_unsupported.py

fix stringify unsupported not catching MutableMapping

---

CHANGELOG.md
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
tests/unit/neptune/new/internal/backends/test_hosted_neptune_backend.py

Call execute operations with list

---

CHANGELOG.md

chore: Update changelog before release

---

CHANGELOG.md
pyproject.toml

Fixed conda package due to improper non-required backoff requirement

---

tests/e2e/standard/test_artifacts.py

chore: Fix flaky test: test_hash_cache

---

tests/e2e/standard/test_artifacts.py

Skiping flaky test

---

CHANGELOG.md
src/neptune/internal/backends/hosted_artifact_operations.py
src/neptune/internal/backends/hosted_neptune_backend.py

Add header to get artifact attribute request to identify which version of artifact flow client supports

Add header to get artifact attribute request

---

tests/e2e/standard/test_artifacts.py
tests/unit/neptune/new/internal/artifacts/test_local_file_hash_storage.py

Tested it locally - hash is working. Also, executed it multiple time - not flickering

chore: rework tests for caching of file hash

---

.github/workflows/release.yml

chore: Add version validation to release action.

---

.pre-commit-config.yaml
CHANGELOG.md

add trufflehog to pre-commit

---

.github/workflows/release.yml

Reverts neptune-ai/neptune-client#1444

Revert "chore: Add version validation to release action."

---

.github/workflows/unit-in-pull-request.yml
CHANGELOG.md
src/neptune/api/requests_utils.py

fix requests import bug

---

CHANGELOG.md
src/neptune/api/requests_utils.py
src/neptune/exceptions.py
src/neptune/internal/backends/swagger_client_wrapper.py

Add handling of projects limits

---

.github/workflows/integrations.yml

bump low version of py for hugginface e2e

---

CHANGELOG.md
src/neptune/internal/utils/git.py
tests/unit/neptune/new/internal/utils/test_git.py

add newline at the end of the diff file

---

src/neptune/internal/operation_processors/async_operation_processor.py

Fixed wrong callback called

---

CHANGELOG.md
src/neptune/common/backends/utils.py
src/neptune/common/utils.py
src/neptune/legacy/internal/api_clients/hosted_api_clients/utils.py
tests/unit/neptune/new/internal/backends/test_hosted_neptune_backend.py

Add support for retry-after mechanism

---

src/neptune/metadata_containers/run.py
tests/unit/neptune/new/client/test_run.py

Flag to enable/disable remote signals (background job)

---

src/neptune/handler.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py
src/neptune/metadata_containers/safe_container.py

chore: Add safety function with default value

---

CHANGELOG.md
src/neptune/internal/operation_processors/async_operation_processor.py

Added more safe checking to last ack

---

src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/safe_container.py

chore: Return Handler from __getitem__

---

.github/workflows/e2e.yml
CHANGELOG.md
src/neptune/metadata_containers/run.py
tests/e2e/standard/test_init.py

Better handle boolean git_ref value

---

tests/unit/neptune/new/internal/operation_processors/test_async_operation_processor.py

Fixed windows unittests

---

src/neptune/cli/clear.py
src/neptune/cli/container_manager.py
src/neptune/cli/sync.py
tests/unit/neptune/new/cli/test_clear.py
tests/unit/neptune/new/cli/test_status.py
tests/unit/neptune/new/cli/test_sync.py
tests/unit/neptune/new/cli/utils.py

Minor tweaks and tests refactors in neptune.cli

---

src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/internal/utils/monotonic_inc_batch_size.py
tests/unit/neptune/new/internal/utils/test_monotonic_inc_batch_size.py

Add dynamic (mon increasing) batch size at async operation processor

---

CHANGELOG.md
src/neptune/__init__.py
src/neptune/internal/extensions.py

Added support for plugins/extensions

---

src/neptune/internal/extensions.py

Fix entrypoints

---

CHANGELOG.md
src/neptune/internal/extensions.py
src/neptune/metadata_containers/run.py
tests/unit/neptune/new/client/test_run.py

revert flag for remote signals

---

CHANGELOG.md
src/neptune/internal/operation_processors/async_operation_processor.py

move error handling to separate method in AsyncOperationProcessor

---

CHANGELOG.md
src/neptune/internal/operation_processors/async_operation_processor.py

abstract some logic to seperate methods for AsyncOperationProcessor

---

CHANGELOG.md
pyproject.toml

Added support for experimental extras

---

CHANGELOG.md
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/project.py
tests/unit/neptune/new/client/abstract_tables_test.py

Add limit parameter to fetch_*_table

---

.github/workflows/e2e.yml
CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/project.py
tests/e2e/standard/test_fetch_tables.py
tests/unit/neptune/new/api/test_searching_entries.py
tests/unit/neptune/new/client/abstract_tables_test.py
tests/unit/neptune/new/internal/backends/test_hosted_client.py

Sorting for `fetch_*_table`

---

src/neptune/internal/backends/hosted_neptune_backend.py
tests/unit/neptune/new/internal/backends/test_hosted_client.py

fix sorting bug

---

.github/workflows/e2e.yml
CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/project.py
tests/e2e/standard/test_fetch_tables.py
tests/unit/neptune/new/api/test_searching_entries.py

Add `ascending` parameter to `fetch_*_table`

---

.github/license_header.txt
.pre-commit-config.yaml
src/neptune/api/dtos.py
src/neptune/internal/constants.py
src/neptune/internal/utils/dependency_tracking.py

Update the year in the license header source file

---

src/neptune/internal/operation_processors/operation_logger.py

fix ProcessorStopSignal default field initialization

---

CHANGELOG.md
src/neptune/handler.py
src/neptune/internal/utils/paths.py
tests/unit/neptune/new/test_handler.py

stringify handler paths

---

pyproject.toml

Pined dev requirements

---

pyproject.toml
src/neptune/core/components/queue/disk_queue.py
src/neptune/internal/operation_processors/operation_logger.py
tests/unit/neptune/new/internal/operation_processors/test_operation_logger.py
tests/unit/neptune/new/test_stringify_unsupported.py

fix pytest warning checking + mypy

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/attributes/atoms/artifact.py
src/neptune/attributes/atoms/file.py
src/neptune/attributes/file_set.py
src/neptune/attributes/series/fetchable_series.py
src/neptune/attributes/series/file_series.py
src/neptune/handler.py
src/neptune/internal/backends/hosted_file_operations.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/offline_neptune_backend.py
src/neptune/internal/backends/utils.py
src/neptune/internal/utils/__init__.py
src/neptune/internal/utils/runningmode.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/metadata_containers_table.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/project.py
src/neptune/typing.py
src/neptune/utils.py
tests/e2e/standard/test_fetch_tables.py
tests/unit/neptune/new/api/test_searching_entries.py
tests/unit/neptune/new/client/abstract_tables_test.py
tests/unit/neptune/new/client/test_run_tables.py
tests/unit/neptune/new/internal/backends/test_hosted_client.py
tests/unit/neptune/new/internal/backends/test_hosted_file_operations.py
tests/unit/neptune/new/internal/backends/test_utils.py

Matched `fetch_*_table()` with UI capabilities

---

CHANGELOG.md
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/utils.py
tests/e2e/standard/test_fetch_tables.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run_tables.py

Parse `datetime` attribute values from string to datetime

---

CHANGELOG.md
src/neptune/management/internal/api.py
tests/e2e/management/test_management.py
tests/unit/neptune/management/internal/test_api.py

`trash_objects()` to raise ProjectNotFound if invalid project name

---

src/neptune/cli/collect.py
src/neptune/cli/containers.py
src/neptune/cli/status.py
src/neptune/cli/sync.py
src/neptune/cli/utils.py
src/neptune/core/components/abstract.py

Applied post-merge suggestions to https://github.com/neptune-ai/neptune-client/pull/1609

Post-merge suggestions of resource management

---

tests/e2e/management/test_management.py
tests/e2e/standard/test_fetch_tables.py

less flaky e2e

---

.github/workflows/integrations.yml

Bump kedro min py version in e2e

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/metadata_containers/metadata_container.py
tests/e2e/standard/test_fetch_tables.py
tests/unit/neptune/new/api/test_searching_entries.py
tests/unit/neptune/new/client/abstract_tables_test.py

Better handle limit in fetch_*_table

---

CHANGELOG.md

Release of 1.9.0

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/nql.py

Fix pagination handling in table fetching

---

CHANGELOG.md
pyproject.toml

Fixed conda package

---

src/neptune/api/searching_entries.py
tests/unit/neptune/new/api/test_searching_entries.py

Add missing args to get_single_page call (fix e2e)

---

.github/neptune_client_pyproject.toml
.github/workflows/integrations.yml
pyproject.toml
tests/e2e/integrations/test_mosaicml.py
tests/e2e/pytest.ini

Add composer e2e tests

---

CHANGELOG.md
src/neptune/internal/utils/requirement_check.py
tests/unit/neptune/new/internal/utils/test_requirement_check.py

cache requirements

---

tests/e2e/standard/test_fetch_tables.py

Flaky test marked as skiped

---

CHANGELOG.md
src/neptune/metadata_containers/model.py
tests/e2e/conftest.py
tests/e2e/standard/test_fetch_tables.py

Introduce querying capabilities to `fetch_model_versions_table`

---

.pre-commit-config.yaml

Switch to fork with Flake8 pyproject Python3.12 support

---

CHANGELOG.md
tests/e2e/management/test_management.py
tests/e2e/standard/test_fetch_tables.py

increase sleep duration in fetch e2e tests

---

src/neptune/internal/backends/hosted_neptune_backend.py

Allow to set step size for leaderboard entries fetching

---

poetry.lock

Poetry lock updated

---

src/neptune/objects/run.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_log_handler.py

Disable background jobs and metadata logging

---

CHANGELOG.md

CHANGELOG fix

---

CHANGELOG.md
src/neptune/integrations/aws/__init__.py
src/neptune/integrations/detectron2/__init__.py
src/neptune/integrations/fastai/__init__.py
src/neptune/integrations/kedro/__init__.py
src/neptune/integrations/lightgbm/__init__.py
src/neptune/integrations/optuna/__init__.py
src/neptune/integrations/pytorch/__init__.py
src/neptune/integrations/sacred/__init__.py
src/neptune/integrations/sklearn/__init__.py
src/neptune/integrations/tensorboard/__init__.py
src/neptune/integrations/tensorflow_keras/__init__.py
src/neptune/integrations/xgboost/__init__.py

fix integration imports

---

src/neptune/internal/hardware/metrics/service/metric_service_factory.py
tests/e2e/standard/test_multiprocessing.py

Fixes after rebase

---

tests/e2e/base.py
tests/e2e/management/test_management.py
tests/e2e/standard/test_cli.py
tests/e2e/standard/test_fetch_tables.py
tests/e2e/standard/test_init.py
tests/e2e/standard/test_stage_transitions.py

Change 'xfail' to 'skip' in e2e tests

---

CHANGELOG.md
src/neptune/internal/backends/hosted_client.py

stop sending x-neptune-legacyclient header

---

CHANGELOG.md
src/neptune/utils.py

TQDM notebook only in notebooks

---

CHANGELOG.md
src/neptune/cli/commands.py
tests/e2e/standard/test_cli.py

Disable command line tool

---

CHANGELOG.md
src/neptune/integrations/pytorch_lightning/__init__.py

Fix PTL import

---

CHANGELOG.md
src/neptune/metadata_containers/run.py

stop using default `sys/name`

---

CHANGELOG.md
src/neptune/objects/abstract.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
src/neptune/typing.py
src/neptune/utils.py

remove `AbstractNeptuneObject`

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/hosted_client.py
src/neptune/internal/backends/hosted_neptune_backend.py
tests/unit/neptune/new/api/test_searching_entries.py

Added `Accept` and `Accept-Encoding` headers to protocol buffer requests

---

tests/e2e/base.py
tests/e2e/standard/test_base.py
tests/e2e/standard/test_fetch_tables.py

Test case for group tags

---

.github/workflows/integrations.yml

Added neptune-fetcher integration tests workflow

---

CHANGELOG.md
dev_requirements.txt
pyproject.toml
src/neptune/envs.py
src/neptune/internal/artifacts/drivers/s3.py
src/neptune/internal/utils/s3.py
tests/e2e/standard/test_artifacts.py
tests/unit/neptune/new/internal/artifacts/drivers/test_s3.py

Remove boto3

---

CHANGELOG.md
src/neptune/attributes/sets/string_set.py
tests/e2e/standard/test_base.py
tests/unit/neptune/new/attributes/sets/test_string_set.py

Disable StringSet clear and remove methods

---

CHANGELOG.md
src/neptune/attributes/series/file_series.py
src/neptune/attributes/series/float_series.py
src/neptune/attributes/series/string_series.py
tests/e2e/standard/test_series.py
tests/unit/neptune/new/attributes/series/test_float_series.py
tests/unit/neptune/new/attributes/series/test_string_series.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py

Disable fetch_last and download_last

---

CHANGELOG.md
src/neptune/attributes/atoms/file.py
src/neptune/attributes/file_set.py
src/neptune/handler.py
tests/e2e/base.py
tests/e2e/standard/test_cli.py
tests/e2e/standard/test_files.py
tests/e2e/standard/test_series.py
tests/unit/neptune/new/attributes/atoms/test_artifact.py
tests/unit/neptune/new/attributes/atoms/test_file.py
tests/unit/neptune/new/attributes/sets/test_file_set.py
tests/unit/neptune/new/client/abstract_experiment_test_mixin.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_handler.py

Disable File related functionality

---

tests/e2e/standard/test_init.py

fix e2e test case for dependency tracking

---

.github/workflows/integrations.yml

Disable integrations schedule

---

tests/e2e/base.py

hotfix e2e test collection

---

CHANGELOG.md
src/neptune/handler.py
tests/unit/neptune/new/test_handler.py

Disable file logging

---

poetry.lock

Poetry lock update

---

.github/workflows/e2e.yml

Do not run management tests as a part of standard

---

src/neptune/core/operation_processors/lazy_operation_processor_wrapper.py
src/neptune/core/operation_processors/offline_operation_processor.py
src/neptune/core/operation_processors/operation_processor.py
src/neptune/core/operation_processors/read_only_operation_processor.py

update imports in core.operation_processors

---

.github/workflows/integrations.yml
.github/workflows/unit-in-pull-request.yml
dev_requirements.txt
tests/e2e/integrations/test_tensorflow_images.py
tests/e2e/pytest.ini
tests/unit/neptune/legacy/internal/utils/test_image.py
tests/unit/neptune/new/internal/utils/test_images.py

move tensorflow tests to integrations

---

.github/workflows/e2e.yml
tests/e2e/integrations/test_tensorflow_images.py

Use importskip for tensorflow

---

tests/e2e/standard/test_fetch_tables.py

fix e2e after adding id generation

---

src/neptune/cli/containers.py

Add support for NEPTUNE_ASYNC_BATCH_SIZE in neptune cli

---

.github/workflows/release.yml

Changed to directly install package when releasing

---

.github/workflows/release.yml

Fixed typo in `neptune-client` package release

---

.github/workflows/e2e.yml
.github/workflows/integrations.yml
.github/workflows/set_neptune_ref.yml
.github/workflows/unit.yml

run workflow from custom branch

---

.github/workflows/e2e.yml
.github/workflows/integrations.yml
.github/workflows/set-neptune-ref.yml
.github/workflows/unit.yml

set-neptune-ref fix

---

src/neptune/internal/backends/nql.py

Add an inequality nql operator

---

.github/workflows/e2e.yml
.github/workflows/integrations.yml

Use environment for e2e and integrations workflow

---

.github/actions/job-notify-v2/action.yml
.github/actions/workflow-notify-v2/action.yml
.github/workflows/e2e.yml
.github/workflows/integrations.yml
.github/workflows/unit.yml

custom slack notification message 2/2

---

src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py

Get rid of printing URL and use custom id instead

---

.github/actions/workflow-notify-v2/action.yml
.github/workflows/unit.yml

fix slack notif on Production

---

.github/actions/job-notify-v2/action.yml
.github/actions/workflow-notify-v2/action.yml
.github/workflows/unit.yml

fix slack notif on Production 1.x

---

CHANGELOG.md
src/neptune/core/operation_processors/async_operation_processor/async_operation_processor.py
src/neptune/core/operation_processors/async_operation_processor/processing_resources.py
src/neptune/core/operation_processors/sync_operation_processor.py
src/neptune/core/operation_processors/utils.py
tests/unit/neptune/new/core/operation_processors/async_operation_processor/test_async_operation_processor.py
tests/unit/neptune/new/core/operation_processors/async_operation_processor/test_processing_resources.py
tests/unit/neptune/new/core/operation_processors/test_sync_operation_processor.py

Add custom id to metadata + change container path

---

src/neptune/attributes/attribute.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
tests/unit/neptune/new/attributes/atoms/test_artifact.py
tests/unit/neptune/new/attributes/atoms/test_float.py
tests/unit/neptune/new/attributes/series/test_float_series.py
tests/unit/neptune/new/attributes/test_attribute_base.py
tests/unit/neptune/new/client/abstract_experiment_test_mixin.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_log_handler.py
tests/unit/neptune/new/test_stringify_unsupported.py

bring NeptuneObject closer to async container creation

---

pyproject.toml

Get rid of `grpcio` from dependencies

---

.github/workflows/e2e.yml

Disabled schedule and on merge e2e tests trigger

---

.github/actions/workflow-notify-v2/action.yml
.github/workflows/dev1.x-e2e.yml
.github/workflows/dev1.x-integrations.yml
.github/workflows/dev1.x-unit.yml
.github/workflows/e2e.yml
.github/workflows/unit.yml

Fix slack notif 1/2

---

.github/actions/job-notify-v2/action.yml
.github/actions/workflow-notify-v2/action.yml
.github/workflows/e2e.yml
.github/workflows/integrations.yml
.github/workflows/set-neptune-ref.yml
.github/workflows/unit.yml

Fix slack notifs 2/2

---

.github/workflows/integrations.yml
.github/workflows/unit.yml

Use Python 3.7.17 instead of 3.7.16

---

src/neptune/internal/backends/api_model.py
src/neptune/internal/backends/hosted_client.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py

Removed unused property from client config

---

.github/workflows/integrations.yml
.github/workflows/unit.yml

Get rid of Python 3.7 on MacOS from unittests matrix

---

tests/e2e/standard/test_init.py

 Add group tags to expected fetched structure

---

CHANGELOG.md
pyproject.toml

Add neptune-api dependency

---

.github/workflows/integrations.yml

No macos with python 3.7 in Integrations matrix

---

.pre-commit-config.yaml
pyproject.toml
src/neptune/core/operation_processors/utils.py
src/neptune/integrations/python_logger.py
src/neptune/internal/backends/hosted_client.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/version.py
tests/unit/neptune/new/internal/backends/test_hosted_neptune_backend.py

Fixed mypy for neptune.version and version refactor

---

tests/e2e/base.py
tests/e2e/standard/test_base.py
tests/e2e/standard/test_fetch_tables.py
tests/e2e/standard/test_init.py

chore(client): Remove env var to test group tags in client

---

CHANGELOG.md
pyproject.toml
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/utils.py
src/neptune/objects/with_backend.py
tests/unit/neptune/new/client/test_run_tables.py

Add a super class to handle backend connection for neptune objects

---

tests/e2e/plot_utils.py

Updated bokeh e2e test

---

src/neptune/core/components/queue/aggregating_disk_queue.py
src/neptune/core/operation_processors/async_operation_processor/async_operation_processor.py
src/neptune/core/operation_processors/async_operation_processor/processing_resources.py
src/neptune/core/operation_processors/async_operation_processor/queue_observer.py
src/neptune/core/operations/utils.py
tests/unit/neptune/new/core/components/queue/test_aggregaring_disk_queue.py
tests/unit/neptune/new/core/operation_processors/async_operation_processor/test_async_operation_processor.py
tests/unit/neptune/new/core/operations/test_operations.py

aggregating batching based on operation step

---

.github/workflows/integrations.yml

chore: Update macOS version in Integrations matrix

---

CHANGELOG.md
src/neptune/core/operation_processors/factory.py
src/neptune/integrations/python_logger.py
src/neptune/internal/backends/factory.py
src/neptune/objects/mode.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
tests/unit/neptune/new/attributes/test_attribute_base.py
tests/unit/neptune/new/client/abstract_experiment_test_mixin.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_log_handler.py
tests/unit/neptune/new/test_logging.py
tests/unit/neptune/new/test_stringify_unsupported.py

Debug mode renamed to disabled

---

CHANGELOG.md
src/neptune/exceptions.py
src/neptune/internal/backends/factory.py
src/neptune/internal/backends/hosted_client.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/utils.py
src/neptune/internal/oauth.py
src/neptune/internal/utils/utils.py
src/neptune/internal/websockets/reconnecting_websocket.py
src/neptune/internal/websockets/websocket_client_adapter.py
src/neptune/internal/websockets/websockets_factory.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
src/neptune/objects/with_backend.py

`proxies` parameter removed

---

src/neptune/api/operation_to_api.py
src/neptune/api/operations.py
src/neptune/core/operations/operation.py
src/neptune/core/operations/operation_visitor.py
src/neptune/objects/neptune_object.py
src/neptune/objects/run.py
tests/unit/neptune/new/api/test_operation_to_api_visitor.py
tests/unit/neptune/new/api/test_operations.py
tests/unit/neptune/new/attributes/test_attribute_base.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_log_handler.py
tests/unit/neptune/new/test_stringify_unsupported.py

Run creation time fixed and offline mode working

---

src/neptune/attributes/attribute.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
src/neptune/objects/with_backend.py
tests/unit/neptune/new/attributes/test_attribute_base.py
tests/unit/neptune/new/client/abstract_experiment_test_mixin.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_log_handler.py
tests/unit/neptune/new/test_stringify_unsupported.py

Internal backend instance renamed to legacy backend

---

src/neptune/core/operations/utils.py

Bugfix operation utils

---

CHANGELOG.md
src/neptune/common/hardware/gauges/gpu.py
src/neptune/common/hardware/gpu/gpu_monitor.py

Fix: Fix GPU power usage and warning

---

CHANGELOG.md
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/nql.py
src/neptune/internal/backends/offline_neptune_backend.py

Adjust neptune-client after endpoint changes

---

pyproject.toml

Follow recommendations from [PEP 561 – Distributing and Packaging Type Information](https://peps.python.org/pep-0561/)

Add py.typed file recommended by PEP 561 (v1.x)

---

CHANGELOG.md
src/neptune/internal/utils/deprecation.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py

Added deprecation warning for model/model_version endpoints

---

src/neptune/internal/oauth.py

chore: Use retry mechanism while refreshing oauth token.

---

.github/actions/test-unit/action.yml
src/neptune/management/internal/api.py

Fix for `AttributeError: 'NoneType' object has no attribute 'username'` error when using `get_*_member_list()` methods

fix: Handle case when `registeredMemberInfo` is None

---

.github/SECURITY.md
README.md
src/neptune/__init__.py
src/neptune/common/exceptions.py
src/neptune/common/hardware/gpu/gpu_monitor.py
src/neptune/common/warnings.py
src/neptune/exceptions.py
src/neptune/handler.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/utils/deprecation.py
src/neptune/management/__init__.py
src/neptune/management/internal/api.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py
src/neptune/types/atoms/file.py
src/neptune/utils.py
src/neptune/version.py

> [!CAUTION]
> Don't merge/release until docs transition is complete.
Changes:
- Minimize README
- Redirect docs URLs to legacy docs site

Update 1.x docs for Legacy deprecation

---

.github/SECURITY.md
.pre-commit-config.yaml
README.md
pyproject.toml
src/neptune/__init__.py
src/neptune/exceptions.py
src/neptune/handler.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/exceptions.py
src/neptune/internal/warnings.py
src/neptune/objects/model.py
src/neptune/objects/model_version.py
src/neptune/objects/neptune_object.py
src/neptune/objects/project.py
src/neptune/objects/run.py
src/neptune/utils.py

> [!CAUTION]
> Don't merge until docs transition is complete.
[DOC-46: Update neptune-client docs](https://linear.app/neptuneai/issue/DOC-46/update-neptune-client-docs)
- Update default README to point to new client or legacy docs
- Redirect docs URLs

Update docs for soft launch
