neptune-ai/neptune-client

neptune/api_exceptions.py
neptune/client.py
neptune/internal/channels/channels_values_sender.py

* Sleep appropriate time when values queue was empty
* Stop gracefully on `join()`
* Log errors using logging module (on DEBUG level)

Improve channels values sending thread

---

neptune/__init__.py
neptune/client.py
neptune/sessions.py

Allow to use proxies. Experimented pass.
Simple example to verify:
1. Create local dynamic port forwarding:
```
ssh -D 9999 user@localhost
```
2. Run the following:
```python
if __name__ == '__main__':
proxies = {"http": "socks5h://127.0.0.1:9999", 'https': 'socks5h://127.0.0.1:9999'}
neptune.init(project_qualified_name='namespace/project', proxies=proxies)
neptune.create_experiment()
neptune.send_metric('Test', 0)
```

Allow proxies usage.

---

neptune/internal/channels/channels_values_sender.py
neptune/internal/threads/hardware_metric_reporting_thread.py

We've been catching HTTP exceptions in the hardware monitoring thread, while our HttpClient wrapped some of those exceptions in Neptune exceptions, which resulted in the thread dying prematurely.

Catch more exceptions in hardware/channel sending threads

---

neptune/backend.py
neptune/exceptions.py
neptune/experiments.py
neptune/internal/backends/client_config.py
neptune/internal/backends/credentials.py
neptune/internal/backends/hosted_neptune_backend.py
neptune/internal/backends/offline_backend.py
neptune/internal/streams/channel_writer.py
neptune/projects.py
tests/neptune/internal/backends/test_hosted_neptune_backend.py

Now when the experiment is restored from neptune server, you can log text
(stdout, stderr, logger) without the fear that the x values will be
the same as the old ones and will be discarded. (see the rationale:
https://spectrum.chat/neptune-community/general/continuing-an-interrupted-experiment~e9fff5f8-c322-48fc-a84f-2ece82e5c630)
Fixes #105

Fix text logging to restored experiment

---

neptune/internal/channels/channels_values_sender.py
neptune/internal/threads/aborting_thread.py
neptune/internal/threads/hardware_metric_reporting_thread.py
neptune/internal/threads/neptune_thread.py
neptune/internal/threads/ping_thread.py
neptune/utils.py

The goal here is to make the following script exit on Python 3.7 and later:
```python
import neptune
neptune.init()
neptune.create_experiment()
```
Before 3.7, when the main thread exited, a `join()` method was called on every daemonic thread. This changed and so we're now checking manually if the main thread still exists.

Fix stopping daemon threads in Python >= 3.7

---

neptune/projects.py

The old docstring was clearly wrong. `add_handler` method is called on the argument, which is supported by `logging.Logger` objects, but not by `logging.Handler` objects.

Fixes docstring of the `logger` argument of `Project.create_experiment` method

---

.gitignore
neptune/internal/backends/offline_backend.py
tests/neptune/internal/backends/test_noop_backend.py
tests/neptune/internal/backends/test_noop_object.py

The fix was to replace `__getattribute__` with `__getattr__` in `NoopBackend` (difference explained [here](https://stackoverflow.com/questions/3278077/difference-between-getattr-vs-getattribute)).
Fixes https://neptune-labs.atlassian.net/browse/NPT-8209 , not sure how to link JIRA issues

Fixes "neptune.init() throws exceptions with combination of ipython and offline-mode"

---

neptune/oauth.py

Thanks for creating this great service!
I'm running Neptune behind a proxy (all certificates are self-signed) and getting the following error when creating an experiment: 
```
neptune.api_exceptions.SSLError: SSL certificate validation failed. Set NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE environment variable to accept self-signed certificates.
```
even though I did set the`NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE` env variable.
It looks as if the env variable is indeed picked up, but the `verify` flag isn't used everywhere. This PR fixes the issue.
I'm not sure what the workflow for this project is, so feel free to close this PR in case it doesn't fit with it.
/ Erik

pass verify when refreshing token

---

neptune/internal/backends/offline_backend.py
tests/neptune/internal/backends/test_noop_object.py

Hi, thanks for the great work. This pull request is an attempt to fix potential problems in offline mode.
Without `__getitem__` access, changes like the following (L375) will break existing code when `offline_mode = True`:
https://github.com/PyTorchLightning/pytorch-lightning/pull/3462
I was trying to get initialization by experiment_id to work, and then I tried offline mode and got an error,
```
Traceback (most recent call last):
File "./scripts/03_train_accel_interiornet_monocular.py", line 656, in <module>
main()
File "./scripts/03_train_accel_interiornet_monocular.py", line 625, in main
experiment_id=latest_checkpoint_dict['log_version'],
File "/opt/anaconda3/envs/fast/lib/python3.6/site-packages/pytorch_lightning/loggers/neptune.py", line 189, in __init__
self._experiment = …
```

Fixes errors caused by getitem access on offline backend.

---

neptune/alpha/internal/hardware/hardware_metric_reporting_job.py
neptune/alpha/internal/init_impl.py

Tested scenario with monitoring to one namespace and in second run (with resume) capturing to second namespace. Works well.

Add custom monitoring namespaces

---

requirements.txt
setup.py

There is no dataclasses package for python>=3.7
since it's in standard library.

Fix dataclasses and python version requirement

---

neptune/new/attributes/namespace.py
tests/neptune/new/test_handler.py

Following samples should be consistent:
1.
```
run['best'] = {'trials/0/a': 1}
run['best'] = {'trials/0/a': 2}
```
2.
```
run['best/trials/0/a'] = 1
run['best'] = {'trials/0/a': 2}
```
3.
```
run['best/trials/0/a'] = 1
run['best/trials/0/a'] = 2
```
Currently first one raises an `MetadataInconsistency` exception in compare of successful execution of 2 followings.

Reassigning dict to Namespace

---

neptune/oauth.py

Raise NeptuneInvalidApiTokenException for 401 http code

---

CHANGELOG.md
neptune/new/attributes/namespace.py
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend.py
neptune/new/internal/backends/neptune_backend_mock.py
neptune/new/internal/run_structure.py
tests/neptune/new/test_handler.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10417
before:
```
import neptune.new as neptunerun = neptune.init()
run['model/params'] = {'a': 3}
run.wait()
params run['model/params'].fetch() == {'model': {'params': {'a': 3}}}
```
after:
```
import neptune.new as neptunerun = neptune.init()
run['model/params'] = {'a': 3}
run.wait()
params run['model/params'].fetch() == {'a': 3}
```
Also refactored `fetch_atom_attribute_values` to make it more unit-testable.

return path from requested prefix instead of root when fetching namespace

---

CHANGELOG.md
neptune/new/exceptions.py
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend_mock.py
neptune/new/internal/backends/project_lookup.py
neptune/new/internal/backends/project_name_lookup.py
neptune/new/internal/get_project_impl.py
neptune/new/internal/init_impl.py
neptune/patterns.py

User is now allowed to provide project name without workspace `common/fastai-integration` -> `fastai-integration`

Applied project lookup new behaviour

---

CHANGELOG.md
neptune/new/exceptions.py
neptune/new/internal/backends/api_model.py
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend.py
neptune/new/internal/backends/neptune_backend_mock.py
neptune/new/internal/backends/project_name_lookup.py
neptune/new/internal/get_project_impl.py
neptune/new/internal/init_impl.py
neptune/patterns.py

User is not able to initialize Neptune without workspace specification:
```neptune.init('project')```
Exceptions list available workspaces and projects to the current user.

Added new projects lookup behavior. Exceptions listing workspaces and projects.

---

neptune/new/run.py

Motivation: when the user sees "Done" printed, they should know that stopping has definitively finished, without any potential for deadlock, I/O errors, you name it.

Moves "Done" in Run.stop to after operation syncing thread is stopped

---

CHANGELOG.md
neptune/new/internal/utils/git.py

Made more consistent with docs: https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#git-information
> If you start a Run from a directory that is a part of the git repo, Neptune will automatically find the .git directory and log information from it.
For example currently when working with Kedro where we run `kedro run` it starts git repository lookup in virtual env path: `/home/rafal/envs/kedro-integration/bin/kedro` instead of current working directory.

Checking current working directory instead of entrypoint when looking for git repository

---

CHANGELOG.md
neptune/new/attributes/atoms/artifact.py
neptune/new/exceptions.py
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend.py
neptune/new/internal/backends/utils.py

ref. https://neptune-labs.atlassian.net/browse/NPT-10843

gracefully handle artifacts' API unavailability

---

.github/workflows/full.yml

* skip Fast.ai integration test on 3.6
* job link instead of workflow in notification

e2e config improvements

---

e2e_tests/integrations/test_pytorch_lightning.py

cf. Backward Incompatible Changes -> Re-define the current_epoch boundary

adapt e2e test to pytorch-lightning 1.6 release

---

CHANGELOG.md
e2e_tests/standard/test_base.py
neptune/new/metadata_containers/project.py

Matching all listed tags instead of any when calling

---

neptune/new/exceptions.py

In ZSH [] has special meaning and extras installation needs to be surrounded by ". This is compatible with other shells.
- Add "" to pip extras installation command in the error message.

Fix pip extras installation in integrations errror

---

CHANGELOG.md
neptune/new/integrations/prophet/__init__.py
setup.py

I am not changing the changelog, as we are not making it official yet.

Include prophet integration

---

CHANGELOG.md
neptune/new/internal/backends/hosted_neptune_backend.py
neptune/new/internal/backends/neptune_backend.py
neptune/new/internal/backends/neptune_backend_mock.py
neptune/new/metadata_containers/metadata_container.py
neptune/new/metadata_containers/model.py
neptune/new/metadata_containers/project.py
tests/neptune/new/client/abstract_tables_test.py
tests/neptune/new/client/test_model_tables.py
tests/neptune/new/client/test_model_version_tables.py
tests/neptune/new/client/test_run_tables.py

Introduce filtering columns when fetching tables

---

.github/actions/publish-tests-result/action.yml
.github/actions/tests-e2e/action.yml
.github/actions/tests/action.yml
.github/workflows/merge_to_master.yml
.github/workflows/minimal_e2e.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
e2e_tests/standard/test_base.py
tests/neptune/internal/channels/test_channels_values_sender.py
tests/neptune/new/client/abstract_experiment_test_mixin.py

* Some tests were decorated to timeout after 10s, those tests caused problems, they will be timeouted by default as all other tests (we keep 120s).
* introduced bot for publishing summary of tests
* junitxml files from all tests are available in artifacts

Fix problems with timeouts in integration tests

---

neptune/management/internal/api.py

Fix some spacing issues that caused the args to render in a weird way in some editors

Adjust formatting in trash_objects() docstring

---

CHANGELOG.md
src/neptune/new/internal/artifacts/local_file_hash_storage.py

Hey everyone,
Artifact tracking appears to be broken when a parent directory contains a SQL special character. The code that I modified (`local_file_hash_storage.py`) assumed that Unix paths could be injected without being escaped into SQL statements -- so I just did the standard `?` SQL escaping. If you are tracking artifacts in a directory that has a parent that contains, for example, `'` (e.g. `Frederick's Workspace/`) would break the SQL queries necessary for tracking artifacts.

Fix Artifact Tracking SQL Injection Bug

---

e2e_tests/conftest.py
e2e_tests/integrations/test_lightning.py
e2e_tests/pytest.ini

- add a new mark to designate relevant tests
- use conditional environment fixture creation to avoid creating new project every time

adjust e2e tests for lightning CI

---

tests/neptune/new/internal/test_disk_queue.py

Fixed the test for disk_queue that caused a crash in Windows.

DiskQueue batch limit test fix

---

src/neptune/new/internal/streams/std_stream_capture_logger.py
tests/unit/neptune/new/internal/test_streams.py

StdStreamCaptureLogger now logs asynchronously to avoid deadlock.

Async logging in StdStreamCaptureLogger

---

src/neptune/new/internal/streams/std_stream_capture_logger.py

I found an issue with the change `close` implementation. It was disabling the logger only after everything is processed in the queue, this can be a problem because other threads can be adding new data to log in the background, so the logger will never close.

Fix close method in StsStreamCaptureLogger

---

src/neptune/new/handler.py

- Resolving NPT-12803
- Fixing bug (missing decorator for append and extend)

Better support for Handler level objects

---

CHANGELOG.md
src/neptune/management/internal/api.py
src/neptune/management/internal/utils.py
src/neptune/new/internal/init/project.py

Deprecate name parameter in init_project and management API

---

CHANGELOG.md
pyproject.toml
src/neptune/new/integrations/aws/__init__.py

We have a new `neptune-aws` module, we want to be able to install it as `pip install neptune[aws]`. 
**Notice:** We are still waiting for Conda to have our package, it's already on PyPI.

Add neptune-aws to pyproject.toml

---

pyproject.toml

We have duplicated links on our PyPI site: https://pypi.org/project/neptune-client/

Duplicated source link removal

---

CHANGELOG.md
src/neptune/handler.py
src/neptune/integrations/python_logger.py
src/neptune/types/atoms/string.py
src/neptune/types/series/string_series.py
src/neptune/types/type_casting.py
src/neptune/utils.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/test_stringify_unsupported.py

Disabled automatic casting to strings

---

CHANGELOG.md
src/neptune/internal/init/model.py
src/neptune/internal/init/model_version.py
src/neptune/metadata_containers/model.py
tests/unit/neptune/new/client/test_model.py
tests/unit/neptune/new/client/test_model_version.py

Remove model and version params

---

CHANGELOG.md
src/neptune/internal/init/run.py
src/neptune/metadata_containers/metadata_container.py
tests/unit/neptune/new/client/test_run.py

Monitoring is off by default for interactive Python kernels

---

CHANGELOG.md
src/neptune/internal/init/project.py
src/neptune/management/internal/api.py
src/neptune/metadata_containers/project.py
tests/e2e/conftest.py
tests/e2e/management/test_management.py
tests/e2e/standard/test_init.py
tests/e2e/utils.py
tests/unit/neptune/new/client/test_model_tables.py
tests/unit/neptune/new/client/test_project.py
tests/unit/neptune/new/client/test_run_tables.py
tests/unit/neptune/new/internal/backends/test_hosted_client.py

Remove `name` parameter in `init_project` and `management` API

---

.github/workflows/release.yml
CHANGELOG.md
README.md
pyproject.toml
src/neptune/__init__.py
src/neptune/common/patches/bravado.py
src/neptune/exceptions.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/utils/deprecation.py
src/neptune/version.py
tests/unit/neptune/new/internal/utils/test_deprecation.py

Package renamed to `neptune` :rocket:

---

CHANGELOG.md
src/neptune/handler.py
tests/unit/neptune/new/test_handler.py

Proper input value type verification for `append` method

---

src/neptune/internal/init/run.py

Change phrasing of warning message about monitoring being disabled that is shown in interactive sessions.

tweak monitoring warning

---

.github/actions/test-e2e/action.yml
.github/actions/test-unit/action.yml
.github/neptune_client_pyproject.toml
pyproject.toml
tests/unit/neptune/new/client/test_model.py

Dataclasses removed from dependencies, bumped upload-artifact version to v3, and parallel unittests

---

CHANGELOG.md
src/neptune/common/backends/utils.py
src/neptune/common/exceptions.py
src/neptune/internal/backends/swagger_client_wrapper.py

Properly handle expired oauth token

---

CHANGELOG.md
src/neptune/vendor/lib_programname.py
tests/unit/neptune/new/test_libprogramname.py

Hi Neptune team, 
We're doing a quick prototype using your library and during the prototyping, we have faced the following easy to fix issue.
If you use a container and pass very long arguments to the container (in our case the orchestrator does it and we have no control over it), the input argument is captured within `sys.argv` and later in the code it will result in exception error `OSError: [Errno 36] File name too long`
In pathlib documents it also mentions that path.is_file() can throw errors like permissions ( in our case filename being too long).
Solution:
you should use error handling. This won't usually happen in the normal execution and only happens in container-based orchestrators as one of the argv could be very long.
We're currently blocked by this issue. We'd appreciate it …

Fix-long-filenames for docker arguments

---

src/neptune/metadata_containers/model.py

Apparently it's enough for the model key to be unique within the project. ([Slack thread](https://neptune-labs.slack.com/archives/C01H1A8DA3X/p1682069076561179))

Correct scope of model key uniqueness

---

CHANGELOG.md
pyproject.toml
src/neptune/integrations/pytorch/__init__.py

add PyTorch integration support

---

CHANGELOG.md
src/neptune/management/__init__.py
src/neptune/management/exceptions.py
src/neptune/management/internal/api.py
src/neptune/management/internal/utils.py
tests/e2e/management/test_management.py
tests/unit/neptune/new/internal/backends/test_hosted_client.py

Invite users to the workspace programmatically

---

pyproject.toml
tests/e2e/integrations/test_huggingface.py

HuggingFace e2e tests started to raise the error: 
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate`: Run `pip install --upgrade accelerate`
Also - some tests don't pass because of the path to cpu monitoring change. For now I wanted to disable those tests, as they cause false alerts while the integration itself is actually working.

Fix HuggingFace e2e

---

CHANGELOG.md
src/neptune/internal/backends/swagger_client_wrapper.py
src/neptune/management/exceptions.py

Added support of active projects exception

---

CHANGELOG.md
src/neptune/internal/utils/git.py

Fix ImportError when git is missing

---

src/neptune/common/utils.py
tests/e2e/standard/test_init.py

fix: Set index = false on every call repo.is_dirty

---

pyproject.toml
tests/e2e/management/test_management.py

After switching to new elasticsearch client code in leaderboard it seems that we need to wait a bit for index refresh after creating test experiments

Wait for elastic index after experiment creation in trashing e2e

---

CHANGELOG.md
pyproject.toml
src/neptune/internal/utils/dependency_tracking.py
src/neptune/metadata_containers/run.py

replace pipreqs with pip freeze

---

src/neptune/exceptions.py

Update `NeedExistingRunForReadOnlyMode` exception message to reference `with_id` instead of the old class-specific parameters.

Fix ID parameter of NeedExistingRunForReadOnlyMode message

---

CHANGELOG.md
src/neptune/internal/utils/dependency_tracking.py
tests/e2e/standard/test_init.py
tests/unit/neptune/new/internal/utils/test_dependency_tracking.py

Misc adjustments to dependency tracking

---

src/neptune/internal/threading/daemon.py
src/neptune/internal/websockets/websocket_signals_background_job.py

- Ensure daemon.py sleeps only when in the WORKING state. 
- Websocket connection not closing during forking process. (it is time-consuming operation that caused significant slowdown during forking)

fix performance issues on forking process (Linux)

---

CHANGELOG.md
src/neptune/cli/__main__.py

Load CLI plug-ins in try..except block to avoid a failure in loading a plug-in to crash entire CLI. Tested locally.

load plug-ins in try..except block

---

CHANGELOG.md
src/neptune/constants.py
src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/internal/operation_processors/offline_operation_processor.py
src/neptune/internal/operation_processors/operation_storage.py
src/neptune/internal/operation_processors/sync_operation_processor.py

allow users to pass neptune data directory as env var

---

src/neptune/metadata_containers/run.py

Removes redundant technical detail from the `dependencies` argument description of the `init_run()` docstring.
- [N/A] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)

Fix description of 'dependencies' argument

---

CHANGELOG.md
src/neptune/attributes/atoms/integer.py
src/neptune/constants.py
src/neptune/internal/types/stringify_value.py
tests/unit/neptune/new/test_stringify_unsupported.py

cast integers outside of 32bits to float in StringifyValue

---

src/neptune/metadata_containers/run.py

Expand and clarify message that is printed when a run is initialized in an interactive kernel.
- [n/a] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)

make interactive warning exceedingly helpful

---

CHANGELOG.md
src/neptune/integrations/python_logger.py
src/neptune/metadata_containers/metadata_container.py

expose _state attribute with a getter method

---

.github/workflows/integrations.yml
CHANGELOG.md
pyproject.toml

setup airflow e2e execution in workflow

---

CHANGELOG.md
src/neptune/__init__.py
src/neptune/cli/__main__.py
src/neptune/cli/clear.py
src/neptune/cli/commands.py
src/neptune/cli/status.py
src/neptune/cli/utils.py
src/neptune/common/exceptions.py
src/neptune/common/utils.py
src/neptune/exceptions.py
src/neptune/handler.py
src/neptune/version.py

cli and docstrings language review

---

CHANGELOG.md
src/neptune/exceptions.py

Fix `NeptuneLimitExceedException` message to take logging hours into account.

Mention logging hours in Neptune limit exception

---

.github/workflows/e2e.yml
CHANGELOG.md
pyproject.toml

bump boto3 required version

---

src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/operations_preprocessor.py
src/neptune/internal/operation.py
src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/internal/threading/daemon.py
tests/unit/neptune/new/internal/backends/test_operations_preprocessor.py

Adding OperationsPreprocessor to AsyncOperationProcessor so that:
* number of actual (efficiently combined) operations can be used to limit the size of a batch,
* number of series appends can be used to limit the size of a batch.

Add OperationsPreprocessor to queueing

---

CHANGELOG.md
src/neptune/common/warnings.py
src/neptune/internal/types/stringify_value.py
tests/unit/neptune/new/test_stringify_unsupported.py

add handling unsupported nans in stringifying_unsupported

---

CHANGELOG.md
src/neptune/exceptions.py
src/neptune/internal/utils/disk_utilization.py
tests/unit/neptune/new/internal/utils/test_disk_utilization.py

Introduce disk utilization error handler

---

CHANGELOG.md
src/neptune/exceptions.py

Clarifies the `MetadataContainerNotFound` exception message.
The current message can be difficult to understand if the user has mistakenly passed a custom/new ID to `with_id`. (Addresses https://github.com/neptune-ai/neptune-client/issues/1541)

clarify MetadataContainerNotFound message

---

CHANGELOG.md
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/utils.py
tests/unit/neptune/new/client/test_project.py

Move prepare_nql_query to a separate function

---

CHANGELOG.md
src/neptune/internal/disk_queue.py
tests/unit/neptune/new/internal/test_disk_queue.py

Added timestamp of operation put to disk queue

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/metadata_containers/metadata_containers_table.py
tests/unit/neptune/new/api/test_searching_entries.py
tests/unit/neptune/new/client/abstract_tables_test.py

Fetch runs table without Bravado deserialization

---

CHANGELOG.md
src/neptune/metadata_containers/run.py
tests/unit/neptune/new/client/test_run.py

Do not create monitoring namespace if all relevant flags are set to False

---

CHANGELOG.md
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py
src/neptune/metadata_containers/utils.py

Docstrings moved to class-level for Neptune Objects

---

CHANGELOG.md
pyproject.toml
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/model_version.py
src/neptune/metadata_containers/project.py
src/neptune/metadata_containers/run.py

- Closes https://github.com/neptune-ai/neptune-client/issues/1335
- Adds a direct requirement of `typing-extensions`
- Makes more visible what modes are available when trying to initialize specific Neptune Objects with a usage of `Literal` typing.
Remember to adjust conda requirements as well after release.
---

Use literals instead of str for Mode typing and `typing-extensions` added as a direct requirement

---

CHANGELOG.md
pyproject.toml
src/neptune/internal/utils/images.py
src/neptune/types/atoms/file.py
tests/e2e/plot_utils.py
tests/e2e/standard/test_files.py
tests/unit/neptune/new/internal/utils/test_images.py

Add support for Seaborn figures

---

CHANGELOG.md
src/neptune/internal/utils/__init__.py
src/neptune/metadata_containers/project.py
tests/unit/neptune/new/client/test_run_tables.py

Better value validation for state parameter of `fetch_*_table`

---

CHANGELOG.md
src/neptune/internal/operation_processors/async_operation_processor.py
src/neptune/internal/operation_processors/operation_logger.py
tests/unit/neptune/new/internal/operation_processors/test_operation_logger.py

Add processor id to `ProcessorStopSignalData`

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/attributes/atoms/artifact.py
src/neptune/attributes/atoms/file.py
src/neptune/attributes/file_set.py
src/neptune/attributes/series/file_series.py
src/neptune/handler.py
src/neptune/internal/backends/hosted_file_operations.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/offline_neptune_backend.py
src/neptune/internal/backends/utils.py
src/neptune/metadata_containers/metadata_container.py
src/neptune/metadata_containers/metadata_containers_table.py
src/neptune/metadata_containers/model.py
src/neptune/metadata_containers/project.py
src/neptune/typing.py
tests/unit/neptune/new/client/abstract_tables_test.py
tests/unit/neptune/new/internal/backends/test_hosted_file_operations.py

Use progress bar in downloading File and FileSet

---

CHANGELOG.md
src/neptune/common/warnings.py

New format:
```bash
[neptune] [warning] /Users/neptune/Library/Application Support/JetBrains/PyCharm2023.3/scratches/scratch_11.py:1: NeptuneDeprecationWarning: You're importing the Neptune client library via the deprecated `neptune.new` module, which will be removed in a future release. Import directly from `neptune` instead.
```

Changed format of warning messages

---

CHANGELOG.md
src/neptune/api/searching_entries.py
src/neptune/attributes/series/fetchable_series.py
src/neptune/internal/backends/hosted_file_operations.py
src/neptune/internal/backends/hosted_neptune_backend.py

Disable progress bar for small fetchings

---

CHANGELOG.md
src/neptune/internal/operation_processors/lazy_operation_processor_wrapper.py
src/neptune/internal/utils/logger.py
src/neptune/metadata_containers/metadata_container.py
tests/e2e/standard/test_cli.py
tests/unit/neptune/new/client/abstract_experiment_test_mixin.py
tests/unit/neptune/new/internal/operation_processors/test_lazy_operation_processor_wrapper.py
tests/unit/neptune/new/test_experiment.py

Lazy initialization of operation processor. Fixes [NPT-14389](https://github.com/neptune-ai/neptune-client/issues/1622)

Lazy initialization of operation processor

---

CHANGELOG.md
src/neptune/common/backends/utils.py

It was removed in https://github.com/neptune-ai/neptune-client/releases/tag/1.8.1

Restored support for SSL verification exception

---

CHANGELOG.md
src/neptune/internal/utils/images.py
src/neptune/types/atoms/file.py
tests/unit/neptune/new/internal/utils/test_images.py

scale images to [0,1] range

---

CHANGELOG.md
src/neptune/internal/operation_processors/lazy_operation_processor_wrapper.py
src/neptune/metadata_containers/metadata_container.py
tests/e2e/standard/test_multiprocessing.py
tests/e2e/standard/test_threading.py
tests/unit/neptune/new/internal/operation_processors/test_lazy_operation_processor_wrapper.py

fix sending from forked container

---

CHANGELOG.md
src/neptune/utils.py

Use `tqdm.auto`

---

CHANGELOG.md
pyproject.toml

Add setuptools as dependency for py >= 3.12

---

CHANGELOG.md
pyproject.toml

Add setuptools as dependency for python >= 3.12

---

CHANGELOG.md
src/neptune/handler.py
tests/e2e/standard/test_base.py
tests/e2e/standard/test_files.py
tests/unit/neptune/new/test_experiment.py
tests/unit/neptune/new/test_handler.py

disable del and pop in handler

---

CHANGELOG.md
src/neptune/internal/backends/utils.py
tests/unit/neptune/new/internal/backends/test_hosted_neptune_backend.py

Fixed compatibility checks with pre-release versions

---

CHANGELOG.md
src/neptune/handler.py
tests/e2e/standard/test_artifacts.py
tests/unit/neptune/new/attributes/atoms/test_artifact.py
tests/unit/neptune/new/test_handler.py

Disable artifact-related methods in handler + deco

---

CHANGELOG.md
src/neptune/internal/backends/hosted_neptune_backend.py

Fixed default params for getAttributesWithPathsFilter

---

CHANGELOG.md
src/neptune/types/atoms/file.py

Clarify autoscale parameter description

---

CHANGELOG.md
src/neptune/api/fetching_series_values.py
src/neptune/attributes/series/fetchable_series.py
src/neptune/attributes/series/float_series.py
src/neptune/attributes/series/string_series.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/offline_neptune_backend.py
tests/unit/neptune/new/api/test_fetching_series_values.py
tests/unit/neptune/new/internal/backends/test_neptune_backend_mock.py

Series values fetching reworked with protocol buffer support

---

CHANGELOG.md
pyproject.toml
src/neptune/attributes/series/file_series.py
tests/e2e/standard/test_series.py
tests/e2e/utils.py
tests/unit/neptune/new/attributes/series/test_file_series.py
tests/unit/neptune/new/internal/utils/test_images.py
tests/unit/neptune/new/test_handler.py
tests/unit/neptune/new/types/atoms/test_file.py
tests/unit/neptune/new/types/test_file_casting.py

Remove pillow from dependencies

---

CHANGELOG.md
src/neptune/api/models.py
src/neptune/api/pagination.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/internal/backends/neptune_backend.py
src/neptune/internal/backends/neptune_backend_mock.py
src/neptune/internal/backends/offline_neptune_backend.py
tests/unit/neptune/new/api/test_models.py
tests/unit/neptune/new/api/test_pagination.py

Endpoints added for enchanced fields search

---

CHANGELOG.md
src/neptune/core/operations/__init__.py
src/neptune/core/operations/operation.py
src/neptune/core/operations/operation_visitor.py
tests/unit/neptune/new/core/operations/__init__.py
tests/unit/neptune/new/core/operations/test_operations.py

Add initial operations

---

CHANGELOG.md
src/neptune/internal/utils/limits.py
src/neptune/objects/run.py
tests/unit/neptune/new/client/test_run.py

when too long raise NeptuneException
max length increased to 128

change handling of too long custom run id

---

CHANGELOG.md
pyproject.toml
tests/e2e/conftest.py
tests/unit/neptune/new/internal/utils/test_git.py

remove gitpython dependency

---

CHANGELOG.md
src/neptune/internal/backends/api_model.py
src/neptune/internal/backends/hosted_neptune_backend.py
src/neptune/metadata_containers/run.py

Make handling of sys/name dependend on config flag

---

CHANGELOG.md
src/neptune/handler.py

Docstring for pop()

---

CHANGELOG.md
src/neptune/attributes/series/float_series.py
tests/unit/neptune/new/attributes/series/test_series.py

decrease FloatSeries batch size to 1

---

src/neptune/metadata_containers/run.py

Improve warning about interactive sessions

---

.github/CODEOWNERS
.github/neptune_client_pyproject.toml
.github/workflows/e2e.yml
.github/workflows/help-command.yml
.github/workflows/integrations.yml
.github/workflows/unit-in-pull-request.yml
.github/workflows/unit.yml
CHANGELOG.md
codecov.yml
pyproject.toml
src/neptune/internal/utils/images.py
src/neptune/legacy/internal/utils/image.py
tests/unit/neptune/new/internal/utils/test_images.py

Fixed support for additional seaborn images

---

CHANGELOG.md
src/neptune/cli/containers.py
src/neptune/internal/threading/daemon.py

Partially delivers https://github.com/neptune-ai/neptune-client/issues/1893

Better error message for HTTPTooManyRequests
